# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swift-demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'AFNetworking', '~> 4.0.1'
  # Pods for Swift-demo

end
