# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'qpos-ios-demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for qpos-ios-demo
pod 'AFNetworking', '~> 4.0.1'
  target 'qpos-ios-demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
